import mongoose from 'mongoose'
import dotenv from 'dotenv'
import path from 'path'
import { Listing } from '../models/Listing.js'

dotenv.config({ path: path.join(process.cwd(), '.env') })

export const defaultListings = [
  {
    listingCode: 'MH-1001',
    title: 'JCB 3DX Super Backhoe Loader',
    subtitle: 'Well maintained, 2022 model with hammer attachment',
    category: 'Backhoe Loaders',
    type: 'Rent',
    rateOrPrice: '₹ 1,800',
    rateUnit: 'per day',
    securityDeposit: '₹ 15,000',
    minDuration: '3 Days',
    operatorIncluded: true,
    modelYear: '2022',
    hoursUsed: '1,450 hrs',
    description: 'Brand new condition JCB with rock breaker and standard bucket. Ready for site deployment.',
    insuranceValidTill: 'Dec 2026',
    ownerName: 'Rakesh Singh',
    ownerPhone: '+91 98765 43210',
    ownerKyc: 'Verified',
    location: { city: 'Lucknow', state: 'Uttar Pradesh', address: 'Transport Nagar, Lucknow' },
    rcNumber: 'UP32-AB-8921',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Approved',
    approvedBy: 'Admin',
    approvalDate: new Date('2025-09-01'),
    status: 'Active',
    availability: 'Available Now',
    isFeatured: true,
    promotionType: 'Featured',
    promotionStartDate: new Date('2025-09-01'),
    promotionEndDate: new Date('2025-09-30'),
    promotionStatus: 'Active',
    promotionViews: 1240,
    isReported: true,
    reportCount: 1,
    reports: [
      {
        reporterName: 'Rahul Mehta',
        reporterEmail: 'rahul.m@example.com',
        reason: 'Fake / Misleading Information',
        description: 'The machine year was originally written as 2024, but seller confirmed 2022.',
        date: new Date('2025-09-12T10:30:00Z'),
        time: '10:30 AM',
        status: 'Pending',
      },
    ],
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 2450,
  },
  {
    listingCode: 'MH-1002',
    title: 'Tata Signa 2823.K Tipper Truck',
    subtitle: 'Heavy-duty 16 CBM box tipper, 2021 model',
    category: 'Dump Trucks',
    type: 'Sale',
    rateOrPrice: '₹ 28,50,000',
    rateUnit: 'lump sum',
    securityDeposit: 'N/A (Full Payment)',
    minDuration: 'Immediate Sale',
    operatorIncluded: false,
    modelYear: '2021',
    hoursUsed: '42,000 km',
    description: 'First owner vehicle with national permit and valid all-India fitness certificate.',
    insuranceValidTill: 'Mar 2027',
    ownerName: 'Sanjeev Kumar',
    ownerPhone: '+91 91234 56780',
    ownerKyc: 'Verified',
    location: { city: 'Delhi', state: 'Delhi', address: 'Sanjay Gandhi Transport Nagar' },
    rcNumber: 'DL01-CD-5678',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Approved',
    approvedBy: 'Admin',
    approvalDate: new Date('2025-09-02'),
    status: 'Active',
    availability: 'Available Now',
    isFeatured: true,
    promotionType: 'Top Listing',
    promotionStartDate: new Date('2025-09-05'),
    promotionEndDate: new Date('2025-10-05'),
    promotionStatus: 'Active',
    promotionViews: 890,
    isReported: true,
    reportCount: 1,
    reports: [
      {
        reporterName: 'Anjali Verma',
        reporterEmail: 'anjali.v@example.com',
        reason: 'Inappropriate Content',
        description: 'Seller initially had an offensive note in description, now corrected.',
        date: new Date('2025-09-11T16:15:00Z'),
        time: '04:15 PM',
        status: 'Resolved',
        actionTaken: 'Listing description reviewed and approved.',
        resolvedAt: new Date('2025-09-12'),
        resolvedBy: 'Admin',
      },
    ],
    image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 1820,
  },
  {
    listingCode: 'MH-1003',
    title: 'Volvo EC210D Heavy Hydraulic Excavator',
    subtitle: 'High performance mining excavator, 2020',
    category: 'Excavators',
    type: 'Rent',
    rateOrPrice: '₹ 2,500',
    rateUnit: 'per day',
    securityDeposit: '₹ 30,000',
    minDuration: '7 Days',
    operatorIncluded: true,
    modelYear: '2020',
    hoursUsed: '3,100 hrs',
    description: 'Equipped with heavy rock bucket. Ready for mining and earthmoving contracts in NCR.',
    insuranceValidTill: 'Nov 2026',
    ownerName: 'Amit Tiwari',
    ownerPhone: '+91 94567 89012',
    ownerKyc: 'Verified',
    location: { city: 'Noida', state: 'Uttar Pradesh', address: 'Sector 62, Noida' },
    rcNumber: 'UP16-EX-9901',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Pending',
    status: 'Pending',
    availability: 'Available Now',
    isFeatured: false,
    promotionType: 'None',
    isReported: false,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 910,
  },
  {
    listingCode: 'MH-1004',
    title: 'CAT 320D Track Excavator',
    subtitle: 'Fuel efficient, ready to work on construction sites',
    category: 'Excavators',
    type: 'Rent',
    rateOrPrice: '₹ 2,200',
    rateUnit: 'per day',
    securityDeposit: '₹ 25,000',
    minDuration: '5 Days',
    operatorIncluded: true,
    modelYear: '2021',
    hoursUsed: '1,890 hrs',
    description: 'Caterpillar 320D in pristine condition with skilled AC-cabin operator included.',
    insuranceValidTill: 'Jan 2027',
    ownerName: 'Pooja Khanna',
    ownerPhone: '+91 98321 65490',
    ownerKyc: 'Verified',
    location: { city: 'Kanpur', state: 'Uttar Pradesh', address: 'Panki Industrial Area, Kanpur' },
    rcNumber: 'UP78-GH-3456',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Approved',
    approvedBy: 'Admin',
    approvalDate: new Date('2025-09-03'),
    status: 'Active',
    availability: 'On Rent',
    isFeatured: true,
    promotionType: 'Spotlight',
    promotionStartDate: new Date('2025-09-08'),
    promotionEndDate: new Date('2025-10-08'),
    promotionStatus: 'Active',
    promotionViews: 1560,
    isReported: false,
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f8?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1541888946425-d0fbb186c5f8?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 3100,
  },
  {
    listingCode: 'MH-1005',
    title: 'Tadano 50 Ton Hydraulic Mobile Crane',
    subtitle: '50 Ton lifting capacity, certified boom',
    category: 'Cranes',
    type: 'Rent',
    rateOrPrice: '₹ 6,500',
    rateUnit: 'per day',
    securityDeposit: '₹ 50,000',
    minDuration: '2 Days',
    operatorIncluded: true,
    modelYear: '2019',
    hoursUsed: '4,200 hrs',
    description: 'Tadano all-terrain mobile crane with third-party load test fitness certification.',
    insuranceValidTill: 'Aug 2026',
    ownerName: 'Vikram Yadav',
    ownerPhone: '+91 97123 45678',
    ownerKyc: 'Verified',
    location: { city: 'Gurgaon', state: 'Haryana', address: 'Udyog Vihar Phase 4, Gurgaon' },
    rcNumber: 'HR26-IJ-7890',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Pending',
    status: 'Pending',
    availability: 'Available Now',
    isFeatured: false,
    promotionType: 'None',
    isReported: true,
    reportCount: 1,
    reports: [
      {
        reporterName: 'Sunil Choudhary',
        reporterEmail: 'sunil.c@infra.com',
        reason: 'Unavailable / Already Sold',
        description: 'Seller said crane is on long lease till November, but marked available.',
        date: new Date('2025-09-10T11:20:00Z'),
        time: '11:20 AM',
        status: 'Pending',
      },
    ],
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 780,
  },
  {
    listingCode: 'MH-1006',
    title: 'Komatsu PC210-10M0 Excavator',
    subtitle: 'Heavy duty earthmoving shovel, 2021',
    category: 'Excavators',
    type: 'Rent',
    rateOrPrice: '₹ 2,400',
    rateUnit: 'per day',
    securityDeposit: '₹ 20,000',
    minDuration: '7 Days',
    operatorIncluded: true,
    modelYear: '2021',
    hoursUsed: '2,450 hrs',
    description: 'Komatsu low-fuel consumption hydraulic excavator with dealer AMC.',
    insuranceValidTill: 'May 2027',
    ownerName: 'Manish Patel',
    ownerPhone: '+91 98250 12345',
    ownerKyc: 'Verified',
    location: { city: 'Jaipur', state: 'Rajasthan', address: 'VKI Area, Jaipur' },
    rcNumber: 'RJ14-MN-9876',
    docStatus: 'Pending Verification',
    approvalStatus: 'Pending',
    status: 'Pending',
    availability: 'Available Now',
    isFeatured: false,
    promotionType: 'None',
    isReported: false,
    image: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1508873696983-2df5293cb32f?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 650,
  },
  {
    listingCode: 'MH-1007',
    title: 'Hamm 311 Compactor Road Roller',
    subtitle: '11 Ton soil compactor with padfoot shell',
    category: 'Road Rollers',
    type: 'Rent',
    rateOrPrice: '₹ 1,600',
    rateUnit: 'per day',
    securityDeposit: '₹ 10,000',
    minDuration: '4 Days',
    operatorIncluded: true,
    modelYear: '2020',
    hoursUsed: '2,900 hrs',
    description: 'High-frequency vibratory roller for highway compaction projects.',
    insuranceValidTill: 'Oct 2026',
    ownerName: 'Rajendra Joshi',
    ownerPhone: '+91 94140 98765',
    ownerKyc: 'Verified',
    location: { city: 'Agra', state: 'Uttar Pradesh', address: 'NH-19 Highway Hub, Agra' },
    rcNumber: 'UP80-RR-1122',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Approved',
    approvedBy: 'Admin',
    approvalDate: new Date('2025-09-04'),
    status: 'Active',
    availability: 'Available Now',
    isFeatured: false,
    promotionType: 'None',
    isReported: false,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 1420,
  },
  {
    listingCode: 'MH-1008',
    title: 'Schwing Stetter Concrete Mixer CP30',
    subtitle: '30 cu.m/hr automated batching plant & transit mixer',
    category: 'Concrete Equipment',
    type: 'Sale',
    rateOrPrice: '₹ 18,50,000',
    rateUnit: 'lump sum',
    securityDeposit: 'N/A',
    minDuration: 'Immediate',
    operatorIncluded: false,
    modelYear: '2021',
    hoursUsed: '3,800 hrs',
    description: 'Complete plant setup with cement silos and aggregate loading hopper.',
    insuranceValidTill: 'Dec 2026',
    ownerName: 'Vikas Logistics & Fleet',
    ownerPhone: '+91 98980 11223',
    ownerKyc: 'Verified',
    location: { city: 'Lucknow', state: 'Uttar Pradesh', address: 'Chinhat Industrial Area, Lucknow' },
    rcNumber: 'UP32-MX-7700',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Approved',
    approvedBy: 'Admin',
    approvalDate: new Date('2025-09-05'),
    status: 'Active',
    availability: 'Sold',
    isFeatured: true,
    promotionType: 'Featured',
    promotionStartDate: new Date('2025-09-10'),
    promotionEndDate: new Date('2025-10-10'),
    promotionStatus: 'Active',
    promotionViews: 940,
    isReported: false,
    image: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 2200,
  },
  {
    listingCode: 'MH-1009',
    title: 'Kirloskar 125 kVA Silent DG Generator',
    subtitle: 'Soundproof diesel generator for heavy commercial sites',
    category: 'Generators',
    type: 'Rent',
    rateOrPrice: '₹ 1,200',
    rateUnit: 'per day',
    securityDeposit: '₹ 8,000',
    minDuration: '2 Days',
    operatorIncluded: false,
    modelYear: '2022',
    hoursUsed: '980 hrs',
    description: 'CPCB-II approved green power generator with automatic AMF control panel.',
    insuranceValidTill: 'Feb 2027',
    ownerName: 'Apex Power Systems',
    ownerPhone: '+91 99112 23344',
    ownerKyc: 'Verified',
    location: { city: 'Delhi', state: 'Delhi', address: 'Okhla Phase 3, New Delhi' },
    rcNumber: 'DL04-DG-5566',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Rejected',
    reviewedBy: 'Admin',
    reviewedAt: new Date('2025-09-06'),
    rejectionReason: 'Invalid RC Document',
    rejectionNote: 'Commercial registration certificate copy is blurry and expired.',
    status: 'Rejected',
    availability: 'Under Maintenance',
    isFeatured: false,
    promotionType: 'None',
    isReported: false,
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1513828583688-c52646db42da?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 510,
  },
  {
    listingCode: 'MH-1010',
    title: 'John Deere 5310 4WD Heavy Tractor',
    subtitle: '55 HP heavy tractor with front loader attachment',
    category: 'Wheel Loaders',
    type: 'Sale',
    rateOrPrice: '₹ 8,40,000',
    rateUnit: 'lump sum',
    securityDeposit: 'N/A',
    minDuration: 'Immediate',
    operatorIncluded: false,
    modelYear: '2020',
    hoursUsed: '1,650 hrs',
    description: 'Single owner tractor with hydraulic power steering and double clutch.',
    insuranceValidTill: 'Apr 2027',
    ownerName: 'Karan Mehta',
    ownerPhone: '+91 97234 56789',
    ownerKyc: 'Verified',
    location: { city: 'Indore', state: 'Madhya Pradesh', address: 'Kshipra Road, Indore' },
    rcNumber: 'MP09-QR-3210',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Approved',
    approvedBy: 'Admin',
    approvalDate: new Date('2025-09-07'),
    status: 'Active',
    availability: 'Available Now',
    isFeatured: false,
    promotionType: 'None',
    isReported: false,
    image: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1592982537447-7440770cbfc9?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 1750,
  },
  {
    listingCode: 'MH-1011',
    title: 'Ashok Leyland 1616 Haulage Truck',
    subtitle: 'Reliable 6-wheeler haulage truck, 2019 model',
    category: 'Dump Trucks',
    type: 'Rent',
    rateOrPrice: '₹ 1,500',
    rateUnit: 'per day',
    securityDeposit: '₹ 12,000',
    minDuration: '5 Days',
    operatorIncluded: true,
    modelYear: '2019',
    hoursUsed: '58,000 km',
    description: 'Open body truck with heavy steel flooring suitable for industrial cargo transit.',
    insuranceValidTill: 'Sep 2026',
    ownerName: 'Rohit Verma',
    ownerPhone: '+91 98450 67890',
    ownerKyc: 'Verified',
    location: { city: 'Bhopal', state: 'Madhya Pradesh', address: 'Govindpura Industrial Area' },
    rcNumber: 'MP04-OP-6543',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Approved',
    approvedBy: 'Admin',
    approvalDate: new Date('2025-09-08'),
    status: 'Active',
    availability: 'On Rent',
    isFeatured: true,
    promotionType: 'Promoted',
    promotionStartDate: new Date('2025-09-05'),
    promotionEndDate: new Date('2025-10-05'),
    promotionStatus: 'Active',
    promotionViews: 610,
    isReported: false,
    image: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 1330,
  },
  {
    listingCode: 'MH-1012',
    title: 'Case 770EX Magnum Backhoe Loader',
    subtitle: '76 HP turbo engine with extended dipper',
    category: 'Backhoe Loaders',
    type: 'Rent',
    rateOrPrice: '₹ 2,000',
    rateUnit: 'per day',
    securityDeposit: '₹ 18,000',
    minDuration: '3 Days',
    operatorIncluded: true,
    modelYear: '2021',
    hoursUsed: '2,100 hrs',
    description: 'Powerful loader with heavy-duty front axle and superior trenching capability.',
    insuranceValidTill: 'Jul 2027',
    ownerName: 'Ankit Trivedi',
    ownerPhone: '+91 99090 12345',
    ownerKyc: 'Verified',
    location: { city: 'Ahmedabad', state: 'Gujarat', address: 'Changodar Industrial Zone' },
    rcNumber: 'GJ05-ST-8765',
    docStatus: 'Uploaded & Clear',
    approvalStatus: 'Approved',
    approvedBy: 'Admin',
    approvalDate: new Date('2025-09-09'),
    status: 'Active',
    availability: 'Available Now',
    isFeatured: false,
    promotionType: 'None',
    isReported: false,
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&auto=format&fit=crop&q=80',
    images: ['https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&auto=format&fit=crop&q=80'],
    viewsCount: 1980,
  },
]

export const seedListings = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI
    if (!mongoUri) throw new Error('MONGODB_URI is not defined in environment')

    if (mongoose.connection.readyState === 0) {
      await mongoose.connect(mongoUri)
      console.log('Connected to MongoDB Atlas for seeding listings...')
    }

    for (const listing of defaultListings) {
      await Listing.findOneAndUpdate(
        { listingCode: listing.listingCode },
        { $set: listing },
        { upsert: true, new: true, runValidators: true }
      )
    }

    const count = await Listing.countDocuments()
    console.log(`Successfully seeded listings into MongoDB Atlas! Total listings: ${count}`)
  } catch (error) {
    console.error('Error seeding listings:', error.message)
  } finally {
    if (process.argv[1]?.includes('seedListings.js')) {
      await mongoose.disconnect()
      console.log('MongoDB connection closed.')
    }
  }
}

if (process.argv[1]?.includes('seedListings.js')) {
  seedListings()
}
